- name: Docker Swarm Worker Joining Playbook
  hosts: docker_swarm_worker
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Install aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'gnupg-agent', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools' ]

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable
        state: present

    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest

    - name: Install required python modules
      pip:
        name:
        - docker
        - jsondiff
        - pyyaml

    - name: Join the docker swarm
      docker_swarm:
        state: join
        advertise_addr: '{{ ansible_default_ipv4.address }}'
        join_token: '{{ worker_secret_token }}'
        remote_addrs: [ '{{ initial_manager_addr }}' ]