- hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3

#minor speedup: install docker on all nodes first.
- hosts: docker_swarm_nodes
  roles:
    - docker

- hosts: docker_swarm_managers
  roles:
    - docker_swarm_create
    
- hosts: docker_swarm_workers
  roles:
    - docker_swarm_join_workers

