- hosts: docker_swarm_managers
  roles:
    - docker_swarm_create
    
- hosts: docker_swarm_workers
  roles:
    - docker_swarm_join_workers
    
- hosts: docker_swarm_managers
  roles:
    - traefik_deployment
      

