- name: Keycloak Setup Playbook
  hosts: all
  tasks:
    - name: Create keycloak user
      user:
        name: keycloak
        shell: /usr/sbin/nologin
        append: yes
        comment: "Keycloak service user"
        state: present
      become: true

    - name: Create keycloak directory
      file:
        path: /etc/keycloak
        state: directory
        owner: keycloak
        group: keycloak
        mode: '0740'

    - name: Download and extract Keycloak archive
      unarchive:
        src: '{{ keycloak_url }}'
        dest: /etc/keycloak
        remote_src: yes
      become: yes
      become_user: keycloak
