- name: Keycloak Setup Playbook
  hosts: all
  tasks:
    - name: Install docker python package
      pip:
        name: docker
    - name: Create keycloak container
      docker_container:
        name: keycloak
        image: "{{ keycloak_container_image }}"
        state: started
        ports:
          - "8080:8080"
        env:
          KEYCLOAK_USER: "{{ default_keycloak_user }}"
          KEYCLOAK_PASSWORD: "{{ default_keycloak_password }}"