# Big shoutout to my homies at DigitalOcean from which I could base the initial docker setup on
# (https://www.digitalocean.com/community/tutorials/how-to-use-ansible-to-install-and-set-up-docker-on-ubuntu-18-04 but we're debian gang instead)

- name: Keycloak Setup Playbook
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
    # Everything below are defaults and generally intended to be overidden in the template
    keycloak_frontend_url: "http://localhost:8080/auth"
    keycloak_container_name: keycloak
    keycloak_external_http_port: 80
    keycloak_external_https_port: 443
    keycloak_db_vendor: h2
    keycloak_db_addr: ''
    keycloak_db_database: keycloak
    keycloak_db_user: ''
    keycloak_db_password: ''
  tasks:
    - name: Install aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'gnupg-agent', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools' ]

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable
        state: present

    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest

    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: Create Keycloak container
      docker_container:
        name: "{{ keycloak_container_name }}"
        image: "{{ keycloak_container_image }}"
        state: started
        restart: yes
        ports:
          - "{{ keycloak_external_http_port }}:8080"
          - "{{ keycloak_external_https_port }}:8443"
        env:
          KEYCLOAK_USER: "{{ default_keycloak_user }}"
          KEYCLOAK_PASSWORD: "{{ default_keycloak_password }}"
          KEYCLOAK_FRONTEND_URL: "{{ keycloak_frontend_url }}"
          DB_VENDOR: "{{ keycloak_db_vendor }}"
          DB_ADDR: "{{ keycloak_db_addr }}"
          DB_DATABASE: "{{ keycloak_db_database }}"
          DB_USER: "{{ keycloak_db_user }}"
          DB_PASSWORD: "{{ keycloak_db_password }}"
