---
# Name of the keycloak container, used for Docker container naming and the postgres storage path
keycloak_container_name: keycloak
# The external port to expose for Postgres
postgres_external_port: 5432
# The directory in which to mount the data directory from Postgres
postgres_data_directory: /etc/postgres-storage/{{ keycloak_container_name }}
# The URL that is used for the base of all routes for Keycloak
keycloak_frontend_url: "http://localhost:8080/auth"