- name: Init new swarm
  docker_swarm:
    state: present
  register: result

- name: Publish the required secrets to be consumed by a workflow
  set_stats:
    data:
      manager_secret_token: '{{ result.swarm_facts.JoinTokens.Manager }}'
      worker_secret_token: '{{ result.swarm_facts.JoinTokens.Worker }}'
      initial_manager_addr: '{{ ansible_default_ipv4.address }}'