- name: Docker Swarm Network Creation Playbook
  hosts: docker_swarm_manager
  vars:
    ansible_python_interpreter: /usr/bin/python3
    # The docker network driver, defaults to 'bridge' but can also be 'overlay' out of the box
    docker_network_driver: 'bridge'
  tasks:
    - name: Install aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'gnupg-agent', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools' ]

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable
        state: present

    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest

    - name: Install required python modules
      pip:
        name:
        - docker
        - jsondiff
        - pyyaml

    - name: Ensure the designated overlay network is created
      docker_network:
        name: '{{ docker_network_name }}'
        driver: '{{ docker_network_driver }}'
        state: present