dependencies:
  - docker
  - role: docker_swarm_network
    vars:
      docker_network_name: "traefik"
      docker_network_driver: "overlay"
  - role: docker_stack_create
    vars:
      stack_name: "traefik"
      service_imbude:
        network_bindpoints: 
          "traefik":
            "acme-store":
              src: "/etc/traefik/acme/"
            "dynamic-traefik-config":
              src: "/etc/traefik/conf.d/"

        traefik:
          "traefik":
            "traefik-dash":
              enabled: TRUE
              route_rule: "Host(`traefik.{{core_domain_name}}`)"
              service_override: "api@internal"
              
      compose:
        version: "3.2"
        services:
          traefik:
            image: traefik
            command:
              - "--api.insecure=true"
              - "--entrypoints.http.address=:80"
              - "--entrypoints.https.address=:443"
              - "--providers.docker"
              - "--providers.docker.swarmmode=true"
              - "--providers.file.directory=/etc/traefik/conf.d/"
              - "--providers.file.watch=true"
            volumes:
              - /var/run/docker.sock:/var/run/docker.sock
            ports:
              - target: 80
                published: 80
              - target: 443
                published: 443
              - target: 8080
                published: 8080
            deploy:
              mode: global
              placement:
                constraints:
                  - node.role == manager
              update_config:
                parallelism: 1
                delay: 10s
              restart_policy:
                condition: on-failure