# Big shoutout to my homies at DigitalOcean from which I could base the initial docker setup on
# (https://www.digitalocean.com/community/tutorials/how-to-use-ansible-to-install-and-set-up-docker-on-ubuntu-18-04 but we're debian gang instead)

- name: Keycloak clustered deployment
  hosts: docker_swarm_manager

- name: Create Postgres database storage directory
  file:
    path: '{{ postgres_data_directory }}'
    state: directory
    mode: '0740'

- name: Create keycloak container stack
  include_role:
    name: 'docker_stack_create'
  vars:
    stack_name: '{{ keycloak_container_name }}'
    compose:
      version: "3"
      networks:
        traefik:
          external:
            name: '{{ traefik_docker_network }}'
      services:
        postgres:
          image: "{{ postgres_container_image }}"
          deploy:
            placement:
              constraints: [ node.role == manager ]
          volumes:
            - '{{ postgres_data_directory }}:/var/lib/postgresql/data'
          ports:
            - '{{ postgres_external_port }}:5432'
          environment:
            POSTGRES_DB: '{{ postgres_db }}'
            POSTGRES_USER: '{{ postgres_user }}'
            POSTGRES_PASSWORD: '{{ postgres_password }}'
        keycloak:
          image: '{{ keycloak_container_image }}' # See https://github.com/ivangfr/keycloak-clustered
          networks:
            - '{{ traefik_docker_network }}'
          deploy:
            mode: global
            labels:
              - 'traefik.enable=true'
              - 'traefik.http.routers.keycloak.rule={{ keycloak_traefik_rule }}'
              - 'traefik.http.services.keycloak-service.loadbalancer.sticky=true'
              - 'traefik.http.services.keycloak-service.loadbalancer.server.port=8080'
              - 'traefik.http.routers.keycloak.service=keycloak-service'
              - 'traefik.docker.network={{ traefik_docker_network }}'
          ports:
            - '7600:7600' # Used for inter-host communications for clustered mode
          environment:
            KEYCLOAK_USER: '{{ default_keycloak_user }}'
            KEYCLOAK_PASSWORD: '{{ default_keycloak_password }}'
            KEYCLOAK_FRONTEND_URL: '{{ keycloak_frontend_url }}'
            DB_VENDOR: postgres
            DB_ADDR: '{{ postgres_address }}'
            DB_DATABASE: '{{ postgres_db }}'
            DB_USER: '{{ postgres_user }}'
            DB_PASSWORD: '{{ postgres_password }}'
            JGROUPS_DISCOVERY_PROTOCOL: JDBC_PING
            JGROUPS_DISCOVERY_PROPERTIES=datasource_jndi_name: java:jboss/datasources/KeycloakDS