- name: Install aptitude using apt
  apt: name=aptitude state=latest cache_valid_time=60 update_cache=yes force_apt_get=yes



- name: Join the docker swarm
  docker_swarm:
    state: join
    advertise_addr: '{{ ansible_default_ipv4.address }}'
    join_token: '{{ worker_secret_token }}'
    remote_addrs: [ '{{ initial_manager_addr }}' ]